### ISSUE TITLE
Required libraries

### ISSUE THREAD

**Issue by kevin-fibich** [User65k/DoorBerryHat#1]
Openening this project in KiCad gives a lot of missing libraries. Can you add the reuired elements to the project or document which libraries should be installed?

**Comment by User65k** [comment]
You are right! I found two *.lib files and uploaded them. KiCad now seems happy with it

**Comment by kevin-fibich** [comment]
Hi, 

my fresh KiCad 5.1.9 with digikey libs is still complaining a lot, here is what it thinks it is missing:

transistors.lib
conn.lib
linear.lib
regul.lib
cmos4000.lib
adc-dac.lib
memory.lib
xilinx.lib
microcontrollers.lib
dsp.lib
microchip.lib
analog_switches.lib
motorola.lib
texas.lib
intel.lib
digital-audio.lib
philips.lib
display.lib
cypress.lib
siliconi.lib
opto.lib
atmel.lib
contrib.lib
valves.lib

I also tried to downgrade to KiCad 4.0.7 which did complain a lot less but still has missing elements like 4N32_1-3, 4N2x1, P1 and more.

**Comment by User65k** [comment]
Interesting - my local backup was different than github. I updated the files. Those should hopefully work (on KiCad 5.1.10)
